name: Docker Image build and push 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        COMMIT_ID=$(git rev-parse --short=6 HEAD)
        echo "commit id is $COMMIT_ID"
        docker build -t razoropsrepocode/coffe:V-$COMMIT_ID .

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
 
    # - name: Build Docker image
    #   run: |
    #     COMMIT_ID=$(git rev-parse --short=6 HEAD)
    #     echo "commit id is $COMMIT_ID"
    #     docker build -t razoropsrepocode/coffe:V-$COMMIT_ID .
    #     # IMAGE_TAG="razoropsrepocode/coffe:V-${COMMIT_ID}"
    #     # docker build -t "$IMAGE_TAG" . 
    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      run: |
          COMMIT_ID=$(git rev-parse --short=6 HEAD)
          # IMAGE_TAG="razoropsrepocode/coffe:V-${COMMIT_ID}"
          # docker push "$IMAGE_TAG"
          docker push razoropsrepocode/coffe:V-$COMMIT_ID
